'use client'
import { useState, useEffect } from 'react'
import ProtectedRoute from '@/components/ProtectedRoute'
import { useAuth } from '@/context/AuthContext'
import api from '@/lib/api'
import { FaPlus, FaEdit, FaTrash, FaImage, FaShoppingCart } from 'react-icons/fa'
import '@/styles/products.css'

function ProductsPage() {
  const { user } = useAuth()
  const isAdmin = user?.role === 'ADMIN'
  const getProductId = (product) => product?._id || product?.id
  const [products, setProducts] = useState([])
  const [loading, setLoading] = useState(true)
  const [showModal, setShowModal] = useState(false)
  const [editingProduct, setEditingProduct] = useState(null)
  const [imageFile, setImageFile] = useState(null)
  const [imagePreview, setImagePreview] = useState(null)
  const [uploadingImage, setUploadingImage] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    price: '',
    quantity: '',
    category: '',
    sku: ''
  })

  // PDF Report Generation for Admins
  const handleGenerateProductReport = async () => {
    const { jsPDF } = await import('jspdf')
    const autoTable = (await import('jspdf-autotable')).default

    const BRAND = [79, 70, 229]
    const GRAY = [107, 114, 128]
    const STRIPE = [245, 247, 255]

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
    const pageW = doc.internal.pageSize.getWidth()
    const pageH = doc.internal.pageSize.getHeight()

    // Header
    doc.setFillColor(...BRAND)
    doc.rect(0, 0, pageW, 30, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(22)
    doc.text('NexMart', 14, 14)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text('Product Report', 14, 22)
    doc.text(
      `Generated: ${new Date().toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })}`,
      pageW - 14,
      22,
      { align: 'right' }
    )

    let y = 40
    const section = (title) => {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(11)
      doc.setTextColor(...BRAND)
      doc.text(title, 14, y)
      doc.setDrawColor(...BRAND)
      doc.setLineWidth(0.3)
      doc.line(14, y + 1.5, pageW - 14, y + 1.5)
      y += 7
    }

    // Product Table
    section('1. Product Overview')
    autoTable(doc, {
      startY: y,
      head: [['Name', 'Category', 'SKU', 'Price', 'Stock', 'Description']],
      body: products.map(p => [
        p.name,
        p.category,
        p.sku,
        `Rs. ${Number(p.price).toLocaleString()}`,
        `${p.quantity} units`,
        p.description
      ]),
      headStyles: { fillColor: BRAND, textColor: 255, fontStyle: 'bold', fontSize: 9 },
      alternateRowStyles: { fillColor: STRIPE },
      styles: { fontSize: 9, cellPadding: 3, overflow: 'linebreak' },
      margin: { left: 14, right: 14 },
      theme: 'grid'
    })

    doc.setFont('helvetica', 'italic')
    doc.setFontSize(9)
    doc.setTextColor(...GRAY)
    doc.text('Generated by NexMart Admin', 14, Math.min(doc.lastAutoTable.finalY + 8, pageH - 14))

    // Footer
    const pages = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(...GRAY)
      doc.text(
        `NexMart Confidential  ·  Page ${i} of ${pages}`,
        pageW / 2,
        pageH - 8,
        { align: 'center' }
      )
    }

    doc.save(`NexMart-Product-Report.pdf`)
  }

  useEffect(() => {
    fetchProducts()
    const interval = setInterval(fetchProducts, 10000)
    return () => clearInterval(interval)
  }, [])

  const fetchProducts = async () => {
    try {
      const response = await api.get(`${process.env.NEXT_PUBLIC_API_INVENTORY_SERVICE}/api/inventory/products`)
      setProducts(response.data)
    } catch (error) {
      console.error('Error fetching products:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    try {
      let productId
      if (editingProduct) {
        productId = getProductId(editingProduct)
        await api.put(
          `${process.env.NEXT_PUBLIC_API_INVENTORY_SERVICE}/api/inventory/products/${productId}`,
          formData
        )
      } else {
        const response = await api.post(
          `${process.env.NEXT_PUBLIC_API_INVENTORY_SERVICE}/api/inventory/products`,
          formData
        )
        productId = response.data.id || response.data._id
      }

      // Upload image if selected
      if (imageFile && productId) {
        await uploadImage(productId)
      }

      setShowModal(false)
      setEditingProduct(null)
      setFormData({ name: '', description: '', price: '', quantity: '', category: '', sku: '' })
      setImageFile(null)
      setImagePreview(null)
      fetchProducts()
    } catch (error) {
      console.error('Error saving product:', error)
      alert(error.response?.data?.message || 'Failed to save product')
    }
  }

  const handleImageChange = (e) => {
    const file = e.target.files[0]
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        alert('Image size should be less than 5MB')
        return
      }
      setImageFile(file)
      setImagePreview(URL.createObjectURL(file))
    }
  }

  const uploadImage = async (productId) => {
    try {
      setUploadingImage(true)
      const formData = new FormData()
      formData.append('image', imageFile)
      
      await api.post(
        `${process.env.NEXT_PUBLIC_API_INVENTORY_SERVICE}/api/inventory/products/${productId}/image`,
        formData,
        {
          headers: {
            'Content-Type': 'multipart/form-data',
          },
        }
      )
    } catch (error) {
      console.error('Error uploading image:', error)
      alert('Failed to upload image')
    } finally {
      setUploadingImage(false)
    }
  }

  const deleteImage = async (productId) => {
    try {
      await api.delete(
        `${process.env.NEXT_PUBLIC_API_INVENTORY_SERVICE}/api/inventory/products/${productId}/image`
      )
      fetchProducts()
    } catch (error) {
      console.error('Error deleting image:', error)
      alert('Failed to delete image')
    }
  }

  const handleEdit = (product) => {
    setEditingProduct(product)
    setFormData({
      name: product.name,
      description: product.description,
      price: product.price,
      quantity: product.quantity,
      category: product.category,
      sku: product.sku
    })
    setImageFile(null)
    setImagePreview(product.imageUrl || null)
    setShowModal(true)
  }

  const handleDelete = async (id) => {
    if (confirm('Are you sure you want to delete this product?')) {
      try {
        await api.delete(`${process.env.NEXT_PUBLIC_API_INVENTORY_SERVICE}/api/inventory/products/${id}`)
        fetchProducts()
      } catch (error) {
        console.error('Error deleting product:', error)
        alert('Failed to delete product')
      }
    }
  }

  const handleAddToCart = async (product) => {
    try {
      const userId = user?._id || user?.id
      await api.post(`${process.env.NEXT_PUBLIC_API_ORDER_SERVICE}/api/cart/add`, {
        userId,
        productId: product.id || product._id,
        quantity: 1
      })
      alert(`"${product.name}" added to cart!`)
    } catch (error) {
      alert(error.response?.data?.message || 'Failed to add to cart')
    }
  }

  if (loading) {
    return <div className="products-loading">Loading products...</div>
  }

  const filteredProducts = products.filter((p) => {
    const q = searchQuery.toLowerCase()
    return (
      p.name?.toLowerCase().includes(q) ||
      p.category?.toLowerCase().includes(q) ||
      p.sku?.toLowerCase().includes(q)
    )
  })

  return (
    <div>
      <div className="products-header">
        <div>
          <h1 className="products-title">Products</h1>
          {!isAdmin && (
            <p className="text-gray-600 mt-1">Browse our product catalog</p>
          )}
        </div>
        {isAdmin && (
          <div style={{ display: 'flex', gap: 12 }}>
            <button
              onClick={() => {
                setEditingProduct(null)
                setFormData({ name: '', description: '', price: '', quantity: '', category: '', sku: '' })
                setImageFile(null)
                setImagePreview(null)
                setShowModal(true)
              }}
              className="products-add-btn"
            >
              <FaPlus />
              Add Product
            </button>
            <button
              onClick={handleGenerateProductReport}
              className="products-add-btn"
              style={{ background: '#4F46E5', color: 'white' }}
            >
              Generate Report
            </button>
          </div>
        )}
      </div>

      <div className="page-search-wrap">
        <input
          type="text"
          className="page-search-input"
          placeholder="Search by name, category, or SKU…"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
        />
      </div>

      <div className="products-grid">
        {filteredProducts.map((product) => (
          <div key={getProductId(product)} className="product-card">
            {product.imageUrl && (
              <div className="product-image-container">
                <img 
                  src={product.imageUrl} 
                  alt={product.name}
                  className="product-image"
                />
              </div>
            )}
            {!product.imageUrl && (
              <div className="product-image-container">
                <div className="product-image-placeholder">
                  <FaImage />
                </div>
              </div>
            )}
            <div className="product-info">
              <h3 className="product-name">{product.name}</h3>
              <p className="product-description">{product.description}</p>
              <div className="product-details">
                <p>
                  <span className="product-detail-label">Price</span>
                  <span className="product-detail-value price">Rs. {product.price?.toLocaleString()}</span>
                </p>
                <p>
                  <span className="product-detail-label">Stock</span>
                  <span className={`product-detail-value ${product.quantity <= 10 ? 'low-stock' : ''}`}>
                    {product.quantity} units
                  </span>
                </p>
                <p>
                  <span className="product-detail-label">Category</span>
                  <span className="product-detail-value">{product.category}</span>
                </p>
                <p>
                  <span className="product-detail-label">SKU</span>
                  <span className="product-detail-value sku">{product.sku}</span>
                </p>
              </div>
              {isAdmin ? (
                <div className="product-actions">
                  <button
                    onClick={() => handleEdit(product)}
                    className="product-edit-btn"
                  >
                    <FaEdit />
                    Edit
                  </button>
                  <button
                    onClick={() => handleDelete(getProductId(product))}
                    className="product-delete-btn"
                  >
                    <FaTrash />
                    Delete
                  </button>
                </div>
              ) : (
                <div className="product-actions">
                  {product.available && product.quantity > 10 ? (
                    <button
                      onClick={() => handleAddToCart(product)}
                      className="product-cart-btn"
                    >
                      <FaShoppingCart />
                      Add to Cart
                    </button>
                  ) : (
                    <span className="product-stock-badge">
                      {product.quantity <= 0 ? 'Out of Stock' : 'Low Stock'}
                    </span>
                  )}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      {showModal && (
        <div className="product-modal-overlay">
          <div className="product-modal">
            <div className="product-modal-header">
              <h2 className="product-modal-title">
                {editingProduct ? 'Edit Product' : 'Add Product'}
              </h2>
              <button
                type="button"
                onClick={() => {
                  setShowModal(false)
                  setImageFile(null)
                  setImagePreview(null)
                }}
                className="product-modal-close"
              >
                ×
              </button>
            </div>
            <form onSubmit={handleSubmit} className="product-modal-form">
              <div className="product-form-group">
                <label>Name</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  required
                />
              </div>
              <div className="product-form-group">
                <label>Description</label>
                <textarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  required
                />
              </div>
              <div className="product-form-group">
                <label>Price</label>
                <input
                  type="number"
                  step="0.01"
                  value={formData.price}
                  onChange={(e) => setFormData({ ...formData, price: e.target.value })}
                  required
                />
              </div>
              <div className="product-form-group">
                <label>Quantity</label>
                <input
                  type="number"
                  value={formData.quantity}
                  onChange={(e) => setFormData({ ...formData, quantity: e.target.value })}
                  required
                />
              </div>
              <div className="product-form-group">
                <label>Category</label>
                <input
                  type="text"
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  required
                />
              </div>
              <div className="product-form-group">
                <label>SKU</label>
                <input
                  type="text"
                  value={formData.sku}
                  onChange={(e) => setFormData({ ...formData, sku: e.target.value })}
                  required
                />
              </div>
              <div className="product-form-group">
                <label>Product Image</label>
                <div className="product-image-zone">
                  {imagePreview ? (
                    <img
                      src={imagePreview}
                      alt="Preview"
                      className="product-image-preview"
                    />
                  ) : (
                    <div className="product-image-zone-placeholder">
                      <span>🖼</span>
                      <span className="product-image-zone-label">Click to upload image</span>
                      <span className="product-image-zone-sub">JPG, PNG, GIF — max 5MB</span>
                    </div>
                  )}
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleImageChange}
                  />
                </div>
              </div>
              <div className="product-modal-actions">
                <button type="submit" className="product-modal-submit" disabled={uploadingImage}>
                  {uploadingImage ? 'Uploading...' : editingProduct ? 'Update' : 'Create'}
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setShowModal(false)
                    setImageFile(null)
                    setImagePreview(null)
                  }}
                  className="product-modal-cancel"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

export default function Page() {
  return (
    <ProtectedRoute>
      <ProductsPage />
    </ProtectedRoute>
  )
}
